### ISSUE TITLE
[Crash] Incompatibility with Create Sifting Refabricated - 1.18.2

### ISSUE THREAD

**Issue by Qhn-bncyqy** [SuperMartijn642/SuperMartijn642sCoreLib#49] opened 2023-09-07 17:41 UTC
**Version Info**
- Minecraft, 1.18.2
- Core Lib 1.1.12a

**Steps to Reproduce**
Put these mods:
- Create Fabric 0.5.1c
- Create Sifting Refabricated 1.3.3g
- CTM 1.0.0
- Core lib 1.1.12a
- Config lib 1.1.8
- Fabric Api 0.76.0
And run the game

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12552019/latest.log)

[crash-2023-09-07_14.31.59-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12552012/crash-2023-09-07_14.31.59-client.txt)

**Comment by SuperMartijn642** [comment] 2023-09-07 18:06
It seems to be caused by Create Sifting Refabricated. Starting the game with just Create and Create Sifting Refabricated installed already crashes.

Anyways, this seems to have nothing to do with my core library, so I'll close the issue.

**Closed as completed by SuperMartijn642** 2023-09-07 18:06 UTC
Labels: crash
