### ISSUE TITLE
Game Crashes on start, 1.19.3 on both 1.1.2 and 1.1.1

### ISSUE THREAD

**Issue by eternalbluepetya** [SuperMartijn642/SuperMartijn642sCoreLib#20] opened 2023-02-19 06:04 UTC
Title is self explanatory. The crash logs seem to mention this lib specifically.
[2023-02-18-3.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10776218/2023-02-18-3.log)

**Comment by SuperMartijn642** [comment] 2023-02-19 11:16
Please use the appropriate template when opening an issue.

> Mod §eaccelerateddecay§r requires §6architectury§r §o7.0.65 or above§r §7Currently, §6architectury§r§7 is §o§nnot installed

It crashes because you haven't installed a mandatory dependency for Accelerated Decay.

Additionally, OptiFine for 1.19.3 does not appear to be compatible with Forge as they list the compatible Forge version as 'N/A'.

Either way, it doesn't appear to be caused by my core library, so I'll close the issue.

**Closed as completed by SuperMartijn642** 2023-02-19 11:16 UTC
