### ISSUE TITLE
[Crash] RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'supermartijn642corelib'!

### ISSUE THREAD

**Issue by levicc00123** [SuperMartijn642/SuperMartijn642sCoreLib#45] opened 2023-08-10 11:10 UTC
**Version Info** 
- Minecraft, 1.19.2 Fabric 0.14.22
- Core Lib, 1.1.12

**Steps to Reproduce**
none, crashes on startup

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12312042/latest.log)

**Comment by SuperMartijn642** [comment] 2023-08-10 11:57
Seems to be caused by a mixin from `porting_lib_base` which is part of `biome_dimensions`. My core library just happens to load a class which they mixin to, which is why the error occurs during preLaunch for my core library.

Please report the issue to `biome_dimensions`.
As far as I can tell this has nothing to do with my core library, so I'll close the issue.

**Closed as completed by SuperMartijn642** 2023-08-10 11:57 UTC
Labels: crash
