### ISSUE TITLE
[Crash] 1.16.5 Server crash on latest update

### ISSUE THREAD

**Issue by Exophobias** [SuperMartijn642/SuperMartijn642sCoreLib#12] opened 2023-01-02 23:47 UTC
**Version Info**
- Minecraft, 1.16.5
- Core Lib, 1.1.0
- Magma, 36.2.39-c1c5a946

**Steps to Reproduce**
Start the server

**Crash report (~/logs/latest.log)**
https://gist.github.com/Exophobias/46e291b1e53635e756fdb6e0cee96a2c

**Other**
The previous version of Core Lib worked fine. Only had issues since I updated this and Wormholes today.

**Comment by ModernGamingWorld** [comment] 2023-01-03 01:20
Same crash I just got as well, I also get a crash from Additional Lanterns cause the mod does not work with the new update

**Comment by JasonKillsUs** [comment] 2023-01-03 07:57
same version same crash

**Comment by Areavate** [comment] 2023-01-03 20:53
I'm having a similar issue with latest update of the core lib 1.1.0,I'm saying "similar" because I don't have a crash report but when I press start in the mc launcher,it start loading the mods suddenly interrupt and I'm back at the mc launcher. I was updating the following mods:trash cans,simplemagnets,entangled and chunk loaders

**Comment by etmoonshade** [comment] 2023-01-04 00:51
[CrashReport 202301031848.zip](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10340695/CrashReport.202301031848.zip)

I'll drop my own crash report (okay, a copy-paste of the log window since I don't have an *actual* crash log) in here just as another data point. Same general pattern - saw updates, updated a bunch of your mods, suddenly crash once I got it all finally updated. :)

**Comment by SuperMartijn642** [comment] 2023-01-04 01:21
I cannot reproduce the issue. Even when running with all my mods, Minecraft starts up fine.
Please make sure all my mods are updated to the latest version.

If you still run into the issue could you note which mods you're using?
Also, the log looks like it might be cut off, but I'm not entirely sure.

**Comment by ModernGamingWorld** [comment] 2023-01-04 01:23
@SuperMartijn642 We all are running into the same crash, by the sounds of it, we all updated all the mods that need to be to their current versions. I myself had to downgrade all of your mods and the core just show I can launch my game again

**Comment by etmoonshade** [comment] 2023-01-04 01:28
Maybe worth mentioning that I'm on Forge 1.16.5-36.2.39? I haven't really tried to troubleshoot it too tightly, I admit - it appears that @Exophobias managed to reproduce the issue with a minimal mod setup though.

**Comment by SuperMartijn642** [comment] 2023-01-04 01:32
Please upload a log from when it crashes. The log provided @Exophobias seems to be caused by some other mod and is likely different from your errors.

**Comment by ModernGamingWorld** [comment] 2023-01-04 01:35
its also worth mentioning I am running at least 400ish mods, so I cant really test without downtime

**Comment by etmoonshade** [comment] 2023-01-04 01:40
@SuperMartijn642 - What you see is what I've got, I'm afraid. Forge must be dying before it has a chance to write any sort of logs, so all I'm able to give is the copy of the Java log that the launcher pops up.

I've checked %appdata%\Roaming\.minecraft\logs and the "logs" folder under my instance directory. If you've got other suggestions, I'm all ears, but I'd expect them to be in one of those two places.

Let me see if I can strip it down to a minimal setup without breaking my Minecraft. Now you've got me curious because you're right - I really _should_ have some sort of more detailed log. :V

**Comment by etmoonshade** [comment] 2023-01-04 01:51
Alright, so: Stripping it down to the following mod list (all downloaded in the past few hours):

-a----        2023-01-03     14:33         108575 entangled-1.3.12-forge-mc1.16.jar
-a----        2023-01-03     18:30          43358 expandability-2.0.1-forge.jar
-a----        2023-01-03     18:29        6693593 journeymap-1.16.5-5.8.5p6.jar
-a----        2023-01-03     18:34         125743 simplemagnets-1.1.9-forge-mc1.16.jar
-a----        2023-01-03     18:26         205206 supermartijn642configlib-1.1.6-forge-mc1.16.jar
-a----        2023-01-03     18:28         467126 supermartijn642corelib-1.1.0-forge-mc1.16.jar
-a----        2023-01-03     18:34        1174792 tesseract-1.0.28-forge-mc1.16.jar
-a----        2023-01-03     18:34         150364 trashcans-1.0.16-forge-mc1.16.jar
-a----        2023-01-03     18:33         312415 wirelesschargers-1.0.7-forge-mc1.16.jar

I still get what appears to be a similar crash to what I pasted in a .zip above.

```[19:43:47] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed supermartijn642corelib.mixins.json:GameDataMixin -> net.minecraftforge.registries.GameData: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on modifyRegisterEvent could not find any targets matching 'lambda$postRegistryEventDispatch$15(Lnet/minecraftforge/fml/IModStateTransition$EventGenerator;)V' in net.minecraftforge.registries.GameData. Using refmap supermartijn642corelib.mixins.refmap.json [PREINJECT Applicator Phase -> supermartijn642corelib.mixins.json:GameDataMixin -> Prepare Injections ->  -> localvar$zzc000$modifyRegisterEvent(Lnet/minecraftforge/event/RegistryEvent$Register;)Lnet/minecraftforge/event/RegistryEvent$Register; -> Parse]``` 
seems to be the error it's throwing when it dies, but I know nowhere near enough about MC mods to tell what it's doing there.

And you're right - I looked back at the crash log I posted, and it lost a LOT of lines. Here's one I copied out of the console line by line. Apologies if I doubled any up, the console window is REALLY stupid about copying stuff out of it, apparently...

[20210103 CrashLog Fixed.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10340894/20210103.CrashLog.Fixed.txt)

**Comment by ModernGamingWorld** [comment] 2023-01-04 01:55
Sounds like a very bad mixin crash somewhere

**Comment by SuperMartijn642** [comment] 2023-01-04 02:36
@etmoonshade thank you. I can indeed reproduce the crash when Expandability is installed. Looking at their code, I am not entirely sure what the issue was, but the change I made seems to work.

Could you check if version 1.1.0a for Minecraft 1.16 fixes the issue?
You can download it here on Modrinth (since CurseForge usually takes a bit to process the files): https://modrinth.com/mod/supermartijn642s-core-lib/versions

**Comment by etmoonshade** [comment] 2023-01-04 02:49
Okay, so interestingly enough...
It allows MC to start successfully on my stripped down version. But when I put it in my fully modded install, not only does it crash, but it crashes before anything even makes it into the console.

And once again it's crashing during the "early loading" process, so I don't (apparently) have any logs in that one other than "waiting for log output"

**Comment by etmoonshade** [comment] 2023-01-04 02:55
Removing Artifacts and Expandability, but leaving the alpha version of your core lib in place, allows me to load Minecraft with my full mod list.

**Comment by SuperMartijn642** [comment] 2023-01-04 03:00
The 1.1.0a version together with both Artifacts and Expandability seems to load fine for me, so not entirely sure what the issue is.
Could you maybe export the profile from the CurseForge launcher and send the zip it gives? Then I can import it and test it myself to see if I can fix it.
![image](https://user-images.githubusercontent.com/12382965/210475674-3746c504-dc31-429a-a330-692bea541373.png)

Thanks for taking the time to help me fix this btw, I do appreciate it 🙂
I am off to bed as it's already 4 am for me, so it will likely be a bit before I respond again.

**Comment by etmoonshade** [comment] 2023-01-04 03:08
FWIW, I'm not doing my mods via any sort of loader like that - I installed Forge by hand and downloaded all the mods individually. I've also been doing a lot of KubeJS edits, though again it seems to be failing well before it even gets to looking at the stuff I've changed.

With that said, here's a copy of the list of mods from my mod folder (without Artifacts and Expandability):

[Custom Modded Modlist.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10341160/Custom.Modded.Modlist.txt)

Note that I'll totally understand if you don't want to rebuild this list by hand, but I imagine that _someone_ else is going to have the right combination of mods to trigger this, and will be able to provide you with some sort of importable export.

Edit: I don't _think_ it breaks any sort of license to zip up the mods I have and send 'em over if it really comes down to it? That's definitely an option.

**Comment by Areavate** [comment] 2023-01-04 08:51
Hey guys,well,I  made a copy of my profile to try again,and upgrading all at once: trash cans,supermarticore lib,simplemagnets,entangled and chunk loaders in my personal modpack,Mc starts with no problem twice in a row while trying the same thing yesterday this had caused some issue(the launcher failed to run mc). I did not modify anything.

**Comment by etmoonshade** [comment] 2023-01-04 16:38
heh. Similar experience here.

My assumption is that there's SOMETHING cached in that old profile that the mod isn't liking.

Creating a new profile and moving all my mods/scripts/etc. (including the Artifacts + Expandability mods) to it allows me to start Minecraft with no issues. Go figure.

Interestingly, moving Artifacts and Expandability into my _existing_ modded directories also allows it to start, so I have no clue what happened now.

At this point, I'm going to chalk the second issue up to "I made SOME sort of mistake last night while trying to troubleshoot/verify this, but I have no clue how or why."

**Comment by SuperMartijn642** [comment] 2023-01-04 18:25
Since the original issue from @Exophobias should be fixed now with version 1.1.0 of my core library, I will close this issue.
If anyone is still running into crashes, please create a new issue with the appropriate information and logs.

Thank you all for reporting the issue and helping me fix it!

**Closed as completed by SuperMartijn642** 2023-01-04 18:25 UTC
Labels: crash
