### ISSUE TITLE
[Crash] On start up

### ISSUE THREAD

**Issue by Sunekaer** [SuperMartijn642/SuperMartijn642sCoreLib#11] opened 2022-04-30 15:05 UTC
**Version Info**
- Minecraft, 1.18.2
- Core Lib,supermartijn642corelib-1.0.17-forge-mc1.18.jar

**Steps to Reproduce**
Start the game

**Crash report (~/logs/latest.log)**
https://pste.me/v1/paste/7J5OF9RXISg/raw

**Comment by Panderine** [comment] 2022-04-30 15:07
same in 1.18.1

Caused by: java.lang.IllegalArgumentException: The specified resource 'supermartijn642corelib.mixins.json' was invalid or could not be read

**Comment by isaaclepes** [comment] 2022-04-30 15:46
Just updated to supermartijn642corelib-1.0.17a-forge-mc1.18.jar, also having this issue.
[debug.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/8597262/debug.log)
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/8597263/latest.log)

**Comment by yessssssssss362** [comment] 2022-04-30 15:49
On 1.16.5 Using Item collectors mod With this one, as soon as I updated this mod from 1.0.16 It crashed the game immediately
Staying on 1.0.16 doesn't break the game

**Comment by rlane85** [comment] 2022-04-30 16:22
Same, rolled back to supermartijn642corelib-1.0.16b-mc1.18.jar and no more crash. Tried with both 1.0.17 and 1.0.17a

Version Info

Minecraft, 1.18.1
Core Lib,supermartijn642corelib-1.0.17-forge-mc1.18.jar
Steps to Reproduce
Start the game

Crash report (crash.txt)

https://pastebin.com/raw/YPZvhncu

**Comment by SuperMartijn642** [comment] 2022-04-30 17:04
Seems I forgot to add the refmap property for the mixins 🤦‍♂️ Since they don't need to be remapped in the dev environment, it worked fine when I tested it. However, as soon as you load it regularly it will break.

It should be fixed now in version 1.0.18. Sorry for the inconvenience and thanks to all of you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-04-30 17:04 UTC
Labels: crash

**Comment by Panderine** [comment] 2022-05-02 01:16
fixed!
