### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by JLSkyzer** [SuperMartijn642/SuperMartijn642sCoreLib#14] opened 2023-01-07 19:50 UTC
**Version Info**
- Minecraft, 1.12.2
- Core Lib

**Steps to Reproduce**
Crash on startup
[crash-2023-01-07_20.00.03-client.txt]

**Crash report (~/logs/latest.log)**
(https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10367081/crash-2023-01-07_20.00.03-client.txt)
[debug.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10367083/debug.log)
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10367084/latest.log)

**Comment by JLSkyzer** [comment] 2023-01-07 19:51
Core lib = Latest

**Comment by SuperMartijn642** [comment] 2023-01-07 20:08
You are using version 1.1.0 of my core library. Please update to 1.1.0a and see if the issue persists.

**Comment by JLSkyzer** [comment] 2023-01-07 20:43
I already use the 1.1.0a and that not work is the reason why i take the 1.1.0

**Comment by JLSkyzer** [comment] 2023-01-07 21:46
and the error is the same

**Comment by Lothloriian** [comment] 2023-01-09 01:55
I'm having a very similar issue that seems to be coming from this particular core lib.  It flagged on the portablemobs but I deleted that one and got the same error for additional lanters.  
![mc crash](https://user-images.githubusercontent.com/114189557/211230309-7403632a-e3d3-4a1f-877f-b106702ed457.png)

**Comment by Lothloriian** [comment] 2023-01-09 01:55
And I tried both separate versions I found of it on curseforge, both together and separate.

**Comment by SuperMartijn642** [comment] 2023-01-09 02:03
@Lothloriian this is completely unrelated to the issue above. Portable Mobs has not been updated for version 1.1 of my core library. All of my own mods have, make sure to update them all.

**Comment by Lothloriian** [comment] 2023-01-09 02:38
Interesting.  I'll try and revert my recent update and see what I find.

**Comment by JLSkyzer** [comment] 2023-01-09 19:26
any idea for my crash ?

**Comment by RedRaspberry** [comment] 2023-01-11 06:18
Having a very similar crash myself with the latest (1.1.1) release
Crashlog is incredibly sparse on info, annoyingly, but I've confirmed it's corelib with a binary search

[crash-2023-01-11_01.09.34-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10389333/crash-2023-01-11_01.09.34-client.txt)

**Comment by ghost** [comment] 2023-01-14 13:49
I found the culprit... apparently, it's a Mixin issue.
Downloaded [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) to fix it and the game is now running fine.
Hope it solves the issue for you too.

Update:
Here is versions I use for the Forge part:
![image](https://user-images.githubusercontent.com/30569881/212477356-60c1bb8f-b16c-45ee-accb-6da01bc0af21.png)

**Comment by SuperMartijn642** [comment] 2023-01-14 13:55
Thanks @SyluxS7, hadn't even thought of that. If that does turn out to be the issue others are experiencing, I will just add Mixin 0.7-0.8 Compatibility as a dependency on CurseForge so hopefully most people won't run in to this issue.

@JLSkyzer and @RedRaspberry, could you check if adding Mixin 0.7-0.8 Compatibility fixes the issue for you too?

**Comment by SyluxS7** [comment] 2023-01-14 15:04
Not sure if the issue is related to this one (i'll create another one if not) but connected glass looks weird from one side :

Side looking glass looks weird:
![wrongside](https://user-images.githubusercontent.com/30569881/212478523-cf3bceb2-7720-4a6c-942e-903f09753ebe.png)

The other side doesn't have this problem :
![goodside](https://user-images.githubusercontent.com/30569881/212478576-47d0de1e-ca2d-48eb-8f67-9864c561534f.png)

**Comment by SuperMartijn642** [comment] 2023-01-14 15:07
That looks like it's has nothing to do with this issue. Could you create an issue for it on Connected Glass' repository?
https://github.com/SuperMartijn642/ConnectedGlass/issues

**Comment by SyluxS7** [comment] 2023-01-14 15:10
Sure!

**Comment by JLSkyzer** [comment] 2023-01-18 09:59
i test that

**Comment by JLSkyzer** [comment] 2023-01-18 10:06
crash again for, he crash on the stage "2/7" 
[crash-2023-01-18_11.06.09-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10444572/crash-2023-01-18_11.06.09-client.txt)

**Comment by JLSkyzer** [comment] 2023-01-18 10:06
LanguageLoader

**Comment by Magic1578** [comment] 2023-01-21 04:24
Game crashes and won't start

Minecraft version: 1.12.2
Forge version: 14.23.5.2860
SuperMartijn642's Core Lib Version: 1.1.1

[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10471491/latest.log)

**Comment by SuperMartijn642** [comment] 2023-01-21 18:17
Finally had some time to actually look into the issue.

@Magic1578 Although a very similar crash, your crash is unrelated to the original issue. This was simply due to a mistake in one of my mixins and because that particular class only rarely gets loaded, it's not particularly obvious.

As for the main issue by @JLSkyzer, the crash only occurs when Hammer Lib, ColorUtility, and my core library are installed. Disable any one of them and the game loads without issue.
It seems to be caused by ColorUtility loading their resources in a hacky way and using an invalid modid (they use capitals in the modid for the resource pack, whilst no capital letters are allowed). Normally ColorUtility doesn't seem to load any translations, however Hammer Lib seems to try to load translations for other mods (no clue why), thus triggering my LanguageLoader for ColorUtility.

This is ultimately an issue with ColorUtility, however I have now added an additional check for cases like this.

Both, the crash from @Magic1578 and from @JLSkyzer, have now been fixed in version 1.1.1a for Minecraft 1.12.
Thank you all for reporting the issues and helping me out!

**Closed as completed by SuperMartijn642** 2023-01-21 18:17 UTC
Labels: crash
